### ISSUE TITLE
Some tips and tricks

### ISSUE THREAD

**Issue by FrankKair** [parapaiva/Digimetal_2#1]
Hey, @parapaiva 

Here are some tips and tricks:

1 - You can use VSCode's Python extension to *lint* the code, making it look more Pythonic (4 spaces indentation, for example);

2 - Python uses *snake_case*, so `CorteSubstrato` should actually be named `corte_substrato` and `intensidadeLimiar` should be `intensidade_limiar` for example;

3 - `if database == 0:` is better as `if not database:`;

4 - A function like `diff_string` could be rewritten like so:

```python
def DiffString(a, b):
    if len(a) > len(b):
        res = a.replace(b, '')  # get diff
    else:
        res = b.replace(a, '')  # get diff
    return res

def diff_string(a, b):
    if len(a) > len(b):
        return a.replace(b, '')

    return b.replace(a, '')
```

5 - When you don't use some returned variables, you can omit them with `_` (underscore):

```python
_, y, _, _ = cv.boundingRect(cnt[0])
```

6 - Try to minimise the use of `global` on your programs, so they're easier to read. One idea is to pass what you need as a function parameter, thus making it easier to understand what every piece of computation needs;

7 - If you have a "main" function, call it like this:

```python
if __name__ == '__main__':
    main_function()
```

8 - Use single quotation marks or double quotation marks, but not both. Usually people use single quotation marks for text and double for string interpolation;

9 - `ToDataFrame_contornos` doesn't receive `database` as parameter and yet uses it;

10 - The text you used in this repository description could be used in a `readme.md` file so that GitHub shows a nice formatted text on your project page 👍 

Hope that helps a little bit! 😊

**Comment by parapaiva** [comment]
Thanks, Frank! I've just finished linting and making these changes. Is the number 8 really necessary? How does it impact on readability?

**Comment by FrankKair** [comment]
It doesn't really impact readability, it's more about using a convention/standard 😊 
It's not a must, more like a good to have.
